[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@balancer/=lib/balancer-v2-monorepo/pkg/interfaces/contracts/", "@openzeppelin/=lib/openzeppelin-contracts/contracts/", "@uniswap-v2/=lib/v2-core/contracts/", "@chainlink-contracts/=lib/chainlink/src/v0.8/", "@layerzero-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
