[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@balancer/=lib/balancer-v2-monorepo/pkg/interfaces/contracts/", "@openzeppelin/=lib/openzeppelin-contracts/contracts/", "@uniswap-v2/=lib/v2-core/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
